name: Build Linux Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: '25'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Eclipse Temurin
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean package jpackage:jpackage

      - name: Configure Build Environment
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
          sudo dpkg-reconfigure man-db
          sudo apt install -y build-essential debhelper devscripts

      - name: Build deb
        run: |
          mkdir -p target/deb
          cp -r debian target/deb
          cd target/deb
          dpkg-buildpackage -us -uc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: target/*.deb
